import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { TheHeader } from '@/components/TheHeader/TheHeader'
import { TheFooter } from '@/components/TheFooter/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<TheHeader />
				<main className='container'>{children}</main>
				<TheFooter />
			</body>
		</html>
	)
}
